name = "vms-command-center"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "VMS_STORAGE"
id = "c49bd43c97844061ba01e4794a8a7dc3"

[env.production]
[[env.production.kv_namespaces]]
binding = "VMS_STORAGE"
id = "YOUR_PRODUCTION_KV_ID"